name: golangci-lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: 'golangci-lint'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

